### ISSUE TITLE
【依頼】フリマアプリ挙動確認	

### ISSUE THREAD

**Issue by Takuya7897** [Takuya7897/furima_28844#9]
入力内容 | 備考
自身のフリマアプリのURL | 本番環境(Heroku)のURL
Web URL:        https://furima28844.herokuapp.com/

Basic認証のIDとパスワード |  
ID: admin  password: 2222
出品者用のメールアドレスとパスワード | 本番環境にて商品出品しているユーザーの情報
メールアドレス: test@test
パスワード: qwqw12

購入者用のメールアドレスとパスワード | 上記とは異なる、本番環境で使用可能なユーザーの情報
メールアドレス:test2@test2
パスワード: qwqw12

購入用カードの番号・期限・セキュリティコード | PAY.JPのテストカード情報

カード番号 | 4242424242424242（16桁）
CVC | 123
有効期限 | 登録時より未来

**Comment by mo1015** [comment]
青山さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
